# helm/prometheus/values.yaml
server:
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        release: eu-cluster


serviceMonitors:
  enabled: true
podMonitors:
  enabled: true

  # extraVolumes:
  #   - name: prometheus-config
  #     configMap:
  #       name: prometheus-config

  # extraVolumeMounts:
  #   - name: prometheus-config
  #     mountPath: /etc/prometheus
  #     readOnly: true

  # configMapOverrideName: "prometheus-config"

# serverFiles:
#   prometheus.yml:
#     global:
#       scrape_interval: 15s
#     scrape_configs:
#       - job_name: 'prometheus'
#         static_configs:
#           - targets: ['localhost:9090']

#       - job_name: 'scaphandre'
#         static_configs:
#           - targets: ['compute.eu-central.svc.cluster.local:8080']

# scrape scaphandre sidecar on compute pods in this namespace
# additionalScrapeConfigs:
#   - job_name: 'scaphandre'
#     static_configs:
#       - targets: ['compute.eu-central.svc.cluster.local:8080']
    # kubernetes_sd_configs:
    #   - role: endpoints
    # relabel_configs:
    #   - source_labels: [__meta_kubernetes_service_name]
    #     regex: 'compute'
    #     action: keep
    #   - source_labels: [__meta_kubernetes_endpoint_port_name]
    #     regex: 'rawmetrics'
    #     action: keep
