apiVersion: v1
kind: Pod
metadata:
  name: hello-energy
spec:
  schedulerName: energy-scheduler
  containers:
  - name: busybox
    image: busybox
    command: ["sh","-c","sleep 3600"]
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
