apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
        - name: benchmark
          image: "{{ .Values.benchmarkImage }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: CENTRALUNIT_URL
              value: "{{ .Values.centralunitURL }}"
