apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralunit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralunit
  template:
    metadata:
      labels:
        app: centralunit
    spec:
      initContainers:
        - name: wait-for-computes
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for compute-0, compute-1, compute-2..."
              until nc -z compute-0.compute 2112; do
                echo "Waiting..."
                sleep 2
              done
      containers:
        - name: centralunit
          image: "gd1.lab.uvalight.net/centralunit:latest"
          ports:
            - containerPort: 2112
          env:
            - name: REGION
              value: "{{ .Values.region }}"
            - name: CLUSTER_NAME
              value: "{{ .Values.clusterName }}"
            - name: CPU_CAPACITY
              value: "{{ .Values.cpuCapacity }}"
            - name: ENERGY_BIAS
              value: "{{ .Values.energyBias }}"
            - name: CARBON_INTENSITY
              value: "{{ .Values.carbonIntensity }}"
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: datavolume
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: centralunit-config
        - name: datavolume
          persistentVolumeClaim:
            claimName: centralunit-pvc
