apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centralunit-pvc
  namespace: eu-central
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "metrics"
  resources:
    requests:
      storage: 1Gi
  volumeName: external-pv
