apiVersion: v1
kind: ConfigMap
metadata:
  name: centralunit-config
data:
  clusters.json: |
    [
    {{- $replicas := int .Values.replicaCount }}
    {{- range $i, $ := until $replicas }}
      {
        "name": "compute-{{ $i }}",
        "metrics_url": "http://compute-{{ $i }}.compute.eu-central.svc.cluster.local:2112",
        "submit_url": "http://compute-{{ $i }}.compute.eu-central.svc.cluster.local:9999"
      }{{ if ne (add1 $i) $replicas }},{{ end }}
    {{- end }}
    ]
  # clusters.json: |
  #   [
  #     {
  #       "name": "eu-fr-paris-1",
  #       "metrics_url": "http://eu-fr-paris-1.compute.eu-central.svc.cluster.local:2112",
  #       "submit_url": "http://eu-fr-paris-1.compute.eu-central.svc.cluster.local:9999",
  #       "region": "eu-central",
  #       "location": "Paris, France",
  #       "cpu_capacity": 32,
  #       "energy_bias": 0.6,
  #       "carbon_intensity": 90,
  #       "latitude": 48.8566,
  #       "longitude": 2.3522
  #     },
  #     {
  #       "name": "eu-de-frankfurt-1",
  #       "metrics_url": "http://eu-de-frankfurt-1.compute.eu-central.svc.cluster.local:2112",
  #       "submit_url": "http://eu-de-frankfurt-1.compute.eu-central.svc.cluster.local:9999",
  #       "region": "eu-central",
  #       "location": "Frankfurt, Germany",
  #       "cpu_capacity": 64,
  #       "energy_bias": 0.5,
  #       "carbon_intensity": 75,
  #       "latitude": 50.1109,
  #       "longitude": 8.6821
  #     },
  #     {
  #       "name": "eu-nl-amsterdam-1",
  #       "metrics_url": "http://eu-nl-amsterdam-1.compute.eu-central.svc.cluster.local:2112",
  #       "submit_url": "http://eu-nl-amsterdam-1.compute.eu-central.svc.cluster.local:9999",
  #       "region": "eu-central",
  #       "location": "Amsterdam, Netherlands",
  #       "cpu_capacity": 48,
  #       "energy_bias": 0.4,
  #       "carbon_intensity": 70,
  #       "latitude": 52.3676,
  #       "longitude": 4.9041
  #     },
  #     {
  #       "name": "eu-it-milan-1",
  #       "metrics_url": "http://eu-it-milan-1.compute.eu-central.svc.cluster.local:2112",
  #       "submit_url": "http://eu-it-milan-1.compute.eu-central.svc.cluster.local:9999",
  #       "region": "eu-central",
  #       "location": "Milan, Italy",
  #       "cpu_capacity": 40,
  #       "energy_bias": 0.55,
  #       "carbon_intensity": 95,
  #       "latitude": 45.4642,
  #       "longitude": 9.19
  #     }
  #   ]

