apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compute
spec:
  serviceName: compute
  replicas: 3
  selector:
    matchLabels:
      app: compute-node
  template:
    metadata:
      labels:
        app: compute-node
    spec:
      containers:
        - name: compute
          image: "goncaloferreirauva/computenode:latest"
          env:
            - name: REGION
              value: "{{ .Values.region }}"
            - name: CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CPU_CAPACITY
              value: "{{ .Values.cpuCapacity }}"
            - name: ENERGY_BIAS
              value: "{{ .Values.energyBias }}"
            - name: CARBON_INTENSITY
              value: "{{ .Values.carbonIntensity }}"
          ports:
            - containerPort: 2112
              name: metrics
          volumeMounts:
            - name: powercap
              mountPath: /sys/class/powercap
            - name: proc
              mountPath: /proc

        - name: scaphandre
          image: hubblo/scaphandre:latest
          securityContext:
            privileged: true
          args:
            - prometheus
            - "--bind"
            - "0.0.0.0:8080"
          ports:
            - containerPort: 8080
              name: scaphandre-metrics
          volumeMounts:
            - name: powercap
              mountPath: /sys/class/powercap
            - name: proc
              mountPath: /proc

      volumes:
        - name: powercap
          hostPath:
            path: /sys/class/powercap
            type: Directory
        - name: proc
          hostPath:
            path: /proc
            type: Directory
