apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-pv
  annotations:
    meta.helm.sh/release-name: eu-cluster
    meta.helm.sh/release-namespace: eu-central
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "metrics"
  hostPath:
    path: /mnt/kubeenergy/data