apiVersion: v1
kind: ConfigMap
metadata:
  name: centralunit-config
data:
  clusters.json: |
    [
    {{- $replicas := int .Values.replicaCount }}
    {{- range $i, $ := until $replicas }}
      {
        "name": "compute-{{ $i }}",
        "metrics_url": "http://compute-{{ $i }}.compute.eu-central.svc.cluster.local:2112",
        "submit_url": "http://compute-{{ $i }}.compute.eu-central.svc.cluster.local:9999"
      }{{ if ne (add1 $i) $replicas }},{{ end }}
    {{- end }}
    ]
