apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compute
spec:
  serviceName: compute
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: compute-node
  template:
    metadata:
      labels:
        app: compute-node
    spec:
      containers:
        - name: compute
          image: g-uva/compute-node:latest
          env:
            - name: REGION
              value: "{{ .Values.region }}"
            - name: CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # e.g., compute-0, compute-1
            - name: CPU_CAPACITY
              value: "{{ .Values.cpuCapacity }}"
            - name: ENERGY_BIAS
              value: "{{ .Values.energyBias }}"
            - name: CARBON_INTENSITY
              value: "{{ .Values.carbonIntensity }}"
          ports:
            - containerPort: 2112
              name: metrics
