apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-node
  labels:
    app: compute-node
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: compute-node
  template:
    metadata:
      labels:
        app: compute-node
    spec:
      containers:
        - name: compute
          image: g-uva/compute-node:latest
          env:
            - name: REGION
              value: "{{ .Values.region }}"
            - name: CLUSTER_NAME
              value: "{{ .Values.clusterName }}"
            - name: CPU_CAPACITY
              value: "{{ .Values.cpuCapacity }}"
            - name: ENERGY_BIAS
              value: "{{ .Values.energyBias }}"
            - name: CARBON_INTENSITY
              value: "{{ .Values.carbonIntensity }}"
